name: phpstan

on: workflow_call

permissions:
  contents: read

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: ./.github/actions/setup-php
        with:
          composer-auth: ${{ secrets.COMPOSER_AUTH }}

      - name: Run PHPStan
        run: ./vendor/bin/phpstan --error-format=github
