name: Pull request pipeline

on: pull_request

permissions:
    contents: write

concurrency:
    group: "${{ github.workflow }}-${{ github.ref_name }}"
    cancel-in-progress: true

jobs:
    lint:
        secrets: inherit
        uses: ./.github/workflows/lint.yml

    tests:
        needs: lint
        if: ${{ needs.lint.outputs.fixedFiles == 'false' }}
        secrets: inherit
        uses: ./.github/workflows/tests.yml

    phpstan:
        needs: lint
        if: ${{ needs.lint.outputs.fixedFiles == 'false' }}
        secrets: inherit
        uses: ./.github/workflows/phpstan.yml

    pipeline-complete:
        name: pipeline-complete
        needs: [lint, tests, phpstan]
        runs-on: ubuntu-latest
        steps:
            - run: echo "All pipeline jobs finished successfully."
